<a href="https://colab.research.google.com/github/SiddhantMS/Statistics/blob/main/sudeep_bhargav_Statics_day6_23_05_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

os.chdir(r"/content/drive/MyDrive/stats")

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='faithful')

In [ ]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [ ]:
x1=df.eruptions

In [ ]:
x1

0      3.600
1      1.800
2      3.333
3      2.283
4      4.533
       ...
267    4.117
268    2.150
269    4.417
270    1.817
271    4.467
Name: eruptions, Length: 272, dtype: float64

In [ ]:
np.mean(x1)

np.float64(3.4877830882352936)

In [ ]:
np.median(x1)

np.float64(4.0)

**Range**: Can be affected by outliers.

**IQR (Interquartile Range)**: 75th percentile - 25th percentile= gives you IQR (3rd - 1st quartile)

**Scipy**

In [ ]:
import scipy
from scipy import stats

In [ ]:
stats.mode(x1)

ModeResult(mode=np.float64(1.867), count=np.int64(8))

In [ ]:
from collections import Counter

In [ ]:
Counter(x1).most_common()

[(1.867, 8),
 (4.5, 8),
 (1.833, 7),
 (4.7, 6),
 (1.75, 6),
 (4.8, 6),
 (4.0, 6),
 (4.533, 5),
 (4.083, 5),
 (3.833, 5),
 (4.333, 5),
 (3.6, 4),
 (1.8, 4),
 (4.35, 4),
 (4.25, 4),
 (1.883, 4),
 (2.0, 4),
 (4.167, 4),
 (4.417, 4),
 (4.6, 4),
 (4.15, 4),
 (4.583, 4),
 (3.917, 3),
 (1.967, 3),
 (2.017, 3),
 (4.567, 3),
 (2.1, 3),
 (4.633, 3),
 (1.817, 3),
 (1.983, 3),
 (4.933, 3),
 (2.2, 3),
 (4.367, 3),
 (4.233, 3),
 (4.45, 3),
 (3.333, 2),
 (2.167, 2),
 (3.85, 2),
 (4.433, 2),
 (4.3, 2),
 (4.467, 2),
 (4.033, 2),
 (4.833, 2),
 (2.233, 2),
 (4.133, 2),
 (4.1, 2),
 (4.067, 2),
 (3.95, 2),
 (4.817, 2),
 (4.667, 2),
 (4.9, 2),
 (1.783, 2),
 (3.767, 2),
 (1.917, 2),
 (2.033, 2),
 (2.4, 2),
 (3.567, 2),
 (3.5, 2),
 (1.933, 2),
 (2.083, 2),
 (2.417, 2),
 (2.25, 2),
 (4.267, 2),
 (4.117, 2),
 (1.85, 2),
 (4.283, 2),
 (2.283, 1),
 (2.883, 1),
 (1.95, 1),
 (4.2, 1),
 (1.6, 1),
 (3.45, 1),
 (3.067, 1),
 (3.367, 1),
 (4.783, 1),
 (3.317, 1),
 (4.716, 1),
 (1.733, 1),
 (4.883, 1),
 (3.717, 1),
 (1.667, 1),
 (4.317, 1),
 (4.4, 1),
 (2.067, 1),
 (5.067, 1),
 (3.883, 1),
 (2.633, 1),
 (4.517, 1),
 (3.75, 1),
 (2.483, 1),
 (4.05, 1),
 (4.85, 1),
 (3.683, 1),
 (4.733, 1),
 (2.3, 1),
 (1.7, 1),
 (2.317, 1),
 (2.617, 1),
 (2.267, 1),
 (4.65, 1),
 (2.8, 1),
 (4.383, 1),
 (3.733, 1),
 (5.1, 1),
 (5.033, 1),
 (3.967, 1),
 (2.367, 1),
 (5.0, 1),
 (4.617, 1),
 (2.183, 1),
 (3.966, 1),
 (4.366, 1),
 (2.383, 1),
 (3.417, 1),
 (4.483, 1),
 (4.55, 1),
 (4.183, 1),
 (2.217, 1),
 (2.333, 1),
 (2.35, 1),
 (2.9, 1),
 (2.133, 1),
 (3.817, 1),
 (4.767, 1),
 (4.75, 1),
 (2.15, 1)]

In [ ]:
max(x1)-min(x1) #1st method to find the range

3.4999999999999996

In [ ]:
np.ptp(x1) # 2nd one

np.float64(3.4999999999999996)

In [ ]:
IQR= np.percentile(x1,75)-np.percentile(x1,25)
IQR

np.float64(2.2915)

devation

In [ ]:
import numpy as np

In [ ]:
x2 = [4,3,6,5,7,9,4,8,7,3]

In [ ]:
np.var(x2)  # population varance

np.float64(4.04)

In [ ]:
np.std(x2)  # population standard varance

np.float64(2.009975124224178)

In [ ]:
np.var(x2, ddof =1)  #sample variance

np.float64(4.488888888888889)

In [ ]:
np.std(x2, ddof =1)   # sample standard varian

np.float64(2.1186998109427604)

skewness and kurtoss

probablity

In [ ]:
import scipy
from scipy.stats import binom

chances of rain on any given day

if i am in Mumbai

what is probablity of

a.it ranins for exactly 10 days

b. it ranins for maximum 10 days

c. it ranins for minimum 10 days

for case c the no included will be 10,11,12,13,14....

In [ ]:
binom.pmf(no of days we want exact these days(equal to days), no of total days where event happen ,what are chances/probablity of event happaning)

binom.pmf(no of days we want upto these days( less than or equal to days), no of total days where event happen ,what are chances/probablity of event happaning)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1558041945.py, line 1)

In [ ]:
pmf = Probability Mass Function

It gives probability of exactly k successes.

binom.pmf(k, n, p)

Where:

k = exact number of successful days/events wanted
n = total trials/days
p = probability of success/event happening in one trial/day


binom.pmf(days, total_days, probability)

SyntaxError: invalid syntax (1174742926.py, line 1)

In [ ]:
#a.
binom.pmf(10,15,0.7)

np.float64(0.20613038097752098)

In [ ]:
#b.
binom.cdf(10,15,.7)   # in this no will include 0 to 10 0,1,2,3,4 ......10
1 - binom.cdf(10,15,.7)       # in this no will incluce 11,12,13,14,15

np.float64(0.5154910592268429)

In [ ]:
#c.

poission distribution

In [ ]:
from scipy.stats import poisson

In [ ]:
poisson.cdf(12,15) #exactly 12 incidents taking place today

np.float64(0.2676110333925769)

In [ ]:
poisson.cdf(12,15)  #upto 12 incidents take place

np.float64(0.2676110333925769)

In [ ]:
1-poisson.cdf(11,15)# minimum 12 incidents take place

np.float64(0.8152482009760685)

In [ ]:
poisson.sf(11,15)  #is equal to 1-poisson.cdf(11,15)

np.float64(0.8152482009760685)

normAL DISTRIBUTION

In [ ]:
from scipy.stats import norm,t

In [ ]:
#mean - 16hr  stdDev - 2.3hr

In [ ]:
norm.cdf(14,16,2.3)  #probablity less than 14 hours

np.float64(0.19226902649831168)

In [ ]:
1-norm.cdf(14,16,2.3) #probablity more than 14 hours
#other option
norm.sf(14,16,2.3)

np.float64(0.8077309735016883)

In [ ]:
.cdf(number at start,mean,std Dev)

In [ ]:
(1-norm.cdf(13,16,2.3)) - (1-norm.cdf(17,16,2.3))  #probablity between 13 and 17

np.float64(0.5720823773874264)

In [ ]:
norm.cdf(14,16,2.3)

np.float64(0.19226902649831168)

In [ ]:
#another method
z= (14-16)/2.3  # the value for wihich we have to calculate probablity -(minus) mean /(divide by) standard devation
norm.cdf(z)

#what is z - it is not possible for any stand dev  so we have to form standatd normal curve
#  z willl be some value on the curve so left side of z is the same of left side of  standard dev  this is how we define the moment

# stand normal curve =  mean = 0 and std dev = 1

np.float64(0.19226902649831168)